version: "3.7"
services:
  app:
    build:
      args:
        user: ${user}
        uid: ${uid}
      context: ./
      dockerfile: .docker/Dockerfile
    image: appcake
    container_name: appcake-app
    restart: unless-stopped
    working_dir: /var/www/
    depends_on:
      - db
    volumes:
      - ./:/var/www
      - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./.docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    environment:
      PHP_IDE_CONFIG: serverName=docker
    networks:
      - appcake

  nginx:
    image: nginx:alpine
    container_name: appcake-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      appcake:
        aliases:
          - app.appcake.local

  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_cake
    volumes:
      - pgdata:/var/lib/postgresql/data
    container_name: appcake-db
    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      - appcake

volumes:
  pgdata:

networks:
  appcake:
    driver: bridge
